In [11]:
#import libraries
import pandas as pd
import numpy as np
import yfinance as yf
import datetime
%matplotlib inline
import matplotlib.pyplot as plt
from datetime import date, timedelta
from trading_strats import StockEvaluations
from tqdm import tqdm
import os
#from ydata_profiling import ProfileReport
import seaborn as sns

In [25]:
# Define the ticker symbol
ticker_symbol = "MSFT"

# Create a Ticker object
ticker = yf.Ticker(ticker_symbol)

# Fetch historical market data for the last 30 days
historical_data = ticker.history(period="1mo")  # data for the last month

historical_data[['Open', 'High', 'Low', 'Close', 'Volume']]

,Open,High,Low,Close,Volume
Date,,,,,
2024-12-18 00:00:00-05:00,451.320007,452.649994,437.019989,437.390015,24444500
2024-12-19 00:00:00-05:00,441.619995,443.179993,436.320007,437.029999,22963700
2024-12-20 00:00:00-05:00,433.109985,443.739990,428.630005,436.600006,64263700
2024-12-23 00:00:00-05:00,436.739990,437.649994,432.829987,435.250000,19152500
2024-12-24 00:00:00-05:00,434.649994,439.600006,434.190002,439.329987,7164500
2024-12-26 00:00:00-05:00,439.079987,440.940002,436.630005,438.109985,8194200
2024-12-27 00:00:00-05:00,434.600006,435.220001,426.350006,430.529999,18117700
2024-12-30 00:00:00-05:00,426.059998,427.549988,421.899994,424.829987,13158700
2024-12-31 00:00:00-05:00,426.100006,426.730011,420.660004,421.500000,13246500
2025-01-02 00:00:00-05:00,425.529999,426.070007,414.850006,418.579987,16896500
2025-01-03 00:00:00-05:00,421.079987,424.029999,419.540009,423.350006,16662900
2025-01-06 00:00:00-05:00,428.000000,434.320007,425.480011,427.850006,20573600
2025-01-07 00:00:00-05:00,429.000000,430.649994,420.799988,422.369995,18139100
2025-01-08 00:00:00-05:00,423.459991,426.970001,421.540009,424.559998,15054600
2025-01-10 00:00:00-05:00,424.630005,424.709991,415.019989,418.950012,20201100
2025-01-13 00:00:00-05:00,415.239990,418.500000,412.290009,417.190002,17604800
2025-01-14 00:00:00-05:00,417.809998,419.739990,410.720001,415.670013,16935900
2025-01-15 00:00:00-05:00,419.130005,428.149994,418.269989,426.309998,19637800
2025-01-16 00:00:00-05:00,428.700012,429.489990,424.390015,424.579987,15300000
2025-01-17 00:00:00-05:00,434.089996,434.480011,428.170013,429.029999,26148000

In [29]:
def options_chain(symbol):

    tk = yf.Ticker(symbol)
    # Expiration dates
    exps = tk.options

    # Get options for each expiration
    options = pd.DataFrame()
    for e in exps:
        opt = tk.option_chain(e)
        opt = pd.DataFrame().append(opt.calls).append(opt.puts)
        opt['expirationDate'] = e
        options = options.append(opt, ignore_index=True)

    # Bizarre error in yfinance that gives the wrong expiration date
    # Add 1 day to get the correct expiration date
    options['expirationDate'] = pd.to_datetime(options['expirationDate']) + datetime.timedelta(days = 1)
    options['dte'] = (options['expirationDate'] - datetime.datetime.today()).dt.days / 365
    
    # Boolean column if the option is a CALL
    options['CALL'] = options['contractSymbol'].str[4:].apply(
        lambda x: "C" in x)
    
    options[['bid', 'ask', 'strike']] = options[['bid', 'ask', 'strike']].apply(pd.to_numeric)
    options['mark'] = (options['bid'] + options['ask']) / 2 # Calculate the midpoint of the bid-ask
    
    # Drop unnecessary and meaningless columns
    options = options.drop(columns = ['contractSize', 'currency', 'change', 'percentChange', 'lastTradeDate', 'lastPrice'])

    return options



options_chain('TSLA')

AttributeError: 'DataFrame' object has no attribute 'append'